(deffacts MAIN::estado-inicial
   (acciones (create$ mono-ve-banana))
   (mono en suelo)
   (mono esta-hambriento)
   (mono lejos-de silla)
   (mono lejos-de escritorio)
   (banana colgando-del techo)
   (banana con cascara)
   (silla en suelo)
   (silla lejos-de escritorio)
   (silla es-ligera)
   (escritorio en suelo)
   (escritorio no-debajo-de banana)
   (escritorio es-pesado))

